"use strict";

import test from "node:test";
import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_DIR = path.join(ROOT, "browser", "standalone");
const PACKAGE = JSON.parse(await readFile(path.join(ROOT, "package.json"), "utf8"));
const BANNER = `/*! Pastafari Calendar v${PACKAGE.version} | standalone classic-script build | generated by npm run build:standalone; do not edit. */`;
const OUTPUTS = Object.freeze([
  "pastafari-date.js",
  "pastafari-date.min.js",
]);

test("standalone artifacts are self-contained classic scripts", async () => {
  const forbidden = [
    ["static import", /\bimport\s+(?!\()/u],
    ["dynamic import", /\bimport\s*\(/u],
    ["import.meta", /\bimport\.meta\b/u],
    ["importScripts", /\bimportScripts\s*\(/u],
    ["module Worker", /\btype\s*:\s*["']module["']/u],
    ["runtime fetch", /\bfetch\s*\(/u],
  ];

  for (const filename of OUTPUTS) {
    const source = await readFile(path.join(OUTPUT_DIR, filename), "utf8");
    assert.ok(source.startsWith(BANNER), `${filename} must carry the generated-file banner`);
    assert.match(source, /PastafariCalendarStandalone/u);
    assert.match(source, /pastafari-date/u);
    for (const [label, pattern] of forbidden) {
      assert.doesNotMatch(source, pattern, `${filename} must not contain ${label}`);
    }
  }
});

test("minified and readable standalone artifacts are complete", async () => {
  const [readable, minified] = await Promise.all(
    OUTPUTS.map((filename) => stat(path.join(OUTPUT_DIR, filename))),
  );
  assert.ok(readable.size > 1_000_000, "readable bundle is unexpectedly small");
  assert.ok(minified.size > 1_000_000, "minified bundle is unexpectedly small");
  assert.ok(minified.size <= readable.size, "minified bundle must not exceed readable bundle");
});

test("the local example loads exactly one classic standalone script", async () => {
  const source = await readFile(path.join(OUTPUT_DIR, "example-file.html"), "utf8");
  const scripts = [...source.matchAll(/<script\b([^>]*)\bsrc=["']([^"']+)["'][^>]*>/giu)];
  assert.equal(scripts.length, 1);
  assert.equal(scripts[0][2], "./pastafari-date.js");
  assert.doesNotMatch(scripts[0][0], /\btype\s*=\s*["']module["']/iu);
  assert.doesNotMatch(source, /https?:\/\//iu);
});
